package com.pft.string.service.api.common.bdo;


// Generated Oct 9, 2014 5:46:57 PM by Hibernate Tools 3.4.0.CR1

/**
 * Assets generated by hbm2java
 */
public class Assets implements java.io.Serializable {

	private int id;
	private String assetHash;
	private String url;
	private String description;
	private String metadata;
	private String serviceToken;
	private String userSession;

	public Assets() {
	}

	public Assets(String assetHash) {
		this.assetHash = assetHash;
	}

	public Assets(String serviceToken, String assetHash, String url, String description, String metadata) {
		this.serviceToken= serviceToken;
		this.assetHash = assetHash;
		this.url = url;
		this.description = description;
		this.metadata = metadata;
	}

	public String getAssetHash() {
		return this.assetHash;
	}

	public void setAssetHash(String assetHash) {
		this.assetHash = assetHash;
	}

	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getMetadata() {
		return this.metadata;
	}

	public void setMetadata(String metadata) {
		this.metadata = metadata;
	}

	public String getServiceToken() {
		return serviceToken;
	}

	public void setServiceToken(String serviceToken) {
		this.serviceToken= serviceToken;
	}

	public String getUserSession() {
		return userSession;
	}

	public void setUserSession(String userSession) {
		this.userSession = userSession;
	}
	
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}
	
}
