package com.pft.string.service.api.common.bdo;

// Generated Oct 9, 2014 5:46:57 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Auditlog generated by hbm2java
 */
public class Auditlog implements java.io.Serializable {

	private int id;
	private String userId;
	private String userGuid;
	private Date loginTime;
	private Date logoutTime;

	public Auditlog() {
	}

	public Auditlog(int id) {
		this.id = id;
	}

	public Auditlog(int id, String userId, String userGuid, Date loginTime,
			Date logoutTime) {
		this.id = id;
		this.userId = userId;
		this.userGuid = userGuid;
		this.loginTime = loginTime;
		this.logoutTime = logoutTime;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public String getUserGuid() {
		return this.userGuid;
	}

	public void setUserGuid(String userGuid) {
		this.userGuid = userGuid;
	}

	public Date getLoginTime() {
		return this.loginTime;
	}

	public void setLoginTime(Date loginTime) {
		this.loginTime = loginTime;
	}

	public Date getLogoutTime() {
		return this.logoutTime;
	}

	public void setLogoutTime(Date logoutTime) {
		this.logoutTime = logoutTime;
	}

}
