package com.pft.string.service.api.common.bdo;

// Generated Oct 9, 2014 5:46:57 PM by Hibernate Tools 3.4.0.CR1

/**
 * Service generated by hbm2java
 */
public class Service implements java.io.Serializable {

	private int id;
	private String serviceName;
	private String serviceToken;
	private Integer isPublic;
	private String serviceDescription;
	private String userSession;

	public String getUserSession() {
		return userSession;
	}

	public void setUserSession(String userSession) {
		this.userSession = userSession;
	}

	public Service() {
	}

	public Service(int id) {
		this.id = id;
	}

	public Service(int id, String serviceName, String serviceToken,
			Integer isPublic, String serviceDescription) {
		this.id = id;
		this.serviceName = serviceName;
		this.serviceToken = serviceToken;
		this.isPublic = isPublic;
		this.serviceDescription = serviceDescription;
	}

	public String getServiceName() {
		return this.serviceName;
	}

	public void setServiceName(String serviceName) {
		this.serviceName = serviceName;
	}

	public String getServiceToken() {
		return this.serviceToken;
	}

	public void setServiceToken(String serviceToken) {
		this.serviceToken = serviceToken;
	}

	public Integer getIsPublic() {
		return this.isPublic;
	}

	public void setIsPublic(Integer isPublic) {
		this.isPublic = isPublic;
	}

	public String getServiceDescription() {
		return this.serviceDescription;
	}

	public void setServiceDescription(String serviceDescription) {
		this.serviceDescription = serviceDescription;
	}
	

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

}
