package com.pft.string.service.api.common.bdo;

// Generated Oct 9, 2014 5:46:57 PM by Hibernate Tools 3.4.0.CR1

/**
 * ServiceRegistry generated by hbm2java
 */
public class ServiceRegistry implements java.io.Serializable {

	private Integer service;
	private String serviceName;
	private String serviceToken;
	private boolean isPublic;
	private String serviceDescription;
	private String userSession;

	public String getUserSession() {
		return userSession;
	}

	public void setUserSession(String userSession) {
		this.userSession = userSession;
	}

	public ServiceRegistry() {
	}

	public ServiceRegistry(boolean isPublic) {
		this.isPublic = isPublic;
	}

	public ServiceRegistry(String serviceName, String serviceToken,
			boolean isPublic, String serviceDescription) {
		this.serviceName = serviceName;
		this.serviceToken = serviceToken;
		this.isPublic = isPublic;
		this.serviceDescription = serviceDescription;
	}

	public Integer getService() {
		return this.service;
	}

	public void setService(Integer service) {
		this.service = service;
	}

	public String getServiceName() {
		return this.serviceName;
	}

	public void setServiceName(String serviceName) {
		this.serviceName = serviceName;
	}

	public String getServiceToken() {
		return this.serviceToken;
	}

	public void setServiceToken(String serviceToken) {
		this.serviceToken = serviceToken;
	}

	public boolean isIsPublic() {
		return this.isPublic;
	}

	public void setIsPublic(boolean isPublic) {
		this.isPublic = isPublic;
	}

	public String getServiceDescription() {
		return this.serviceDescription;
	}

	public void setServiceDescription(String serviceDescription) {
		this.serviceDescription = serviceDescription;
	}

}
