package com.pft.string.service.api.common.bdo;

// Generated Oct 9, 2014 5:46:57 PM by Hibernate Tools 3.4.0.CR1

/**
 * Users generated by hbm2java
 */
public class Users implements java.io.Serializable {

	private int id;
	private String username;
	private String password;
	private String oldPassword;
	private String userGuid;
	private String email;
	private boolean isAdmin;
	private String userSession;

	public String getUserSession() {
		return userSession;
	}

	public void setUserSession(String userSession) {
		this.userSession = userSession;
	}

	public Users() {
	}

	public Users(int id, boolean isAdmin) {
		this.id = id;
		this.isAdmin = isAdmin;
	}

	public Users(int id, String username, String password, String userGuid, String email,
			boolean isAdmin) {
		this.id = id;
		this.username=username;
		this.password = password;
		this.userGuid = userGuid;
		this.email = email;
		this.isAdmin = isAdmin;
	}

	public String getUsername() {
		return username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getOldPassword() {
		return this.oldPassword;
	}

	public void setOldPassword(String oldPassword) {
		this.oldPassword = oldPassword;
	}

	public String getUserGuid() {
		return this.userGuid;
	}

	public void setUserGuid(String userGuid) {
		this.userGuid = userGuid;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public boolean isIsAdmin() {
		return this.isAdmin;
	}

	public void setIsAdmin(boolean isAdmin) {
		this.isAdmin = isAdmin;
	}

}
